services:
  qwen-tts:
    build:
      context: .
      args:
        INSTALL_FLASH_ATTN: 1
    container_name: qwen-tts-service
    runtime: nvidia
    ports:
      - "8188:8188"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - QWEN3_TTS_ATTN_IMPLEMENTATION=flash_attention_2
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_PATH=/app/models
      - SAMPLING_RATE=24000
      - TORCH_CUDA_ARCH_LIST=8.0 8.6 8.9 9.0 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]